config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  as :user do
    get '/user', to: 'books#dashboard', as: :user_root
  end

  root to: 'pages#home'

  resources :books do
    collection do
      get 'dashboard'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def dashboard
    client = Goodreads::Client.new(api_key: ENV['GOODREADS_KEY'], api_secret: ENV['GOODREADS_SECRET'])

    if params[:search].present? && params[:search][:query].present?
      @books = client.search_books(params[:search][:query])
      respond_to do |format|
        # format.html
        format.js { render partial: 'search-results'}
      end
    end
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_results.html.erb
<div class="row justify-content-center mt-5">
  <% if @books %>
    <% @books.results.work.each do |book| %>
      <div class="book-card text-center col-12 col-sm-4 col-md-3 col-lg-2 mx-lg-2">
        <div class="content mx-auto" style="background-image: url(<%= book.best_book.image_url %>)">
          <div class="content-details">
            <%= link_to "Add to books", dashboard_books_path, class: 'content-text' %>
          </div>
        </div>
        <h6><%= book.best_book.title %></h6>
        <p><em>by</em> <%= book.best_book.author.name %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/books/_search-results.js.erb
// Defines an annonymous function that call itself with the last ()
(() => {
  const searchResults = document.querySelector('#search-results');

  searchResults.innerHTML = "<%= escape_javascript(render :partial => 'results') %>";
})()

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/dashboard.html.erb
<div class="row mt-5">
  <div class="col-12">
    <h4>Search a book by title, author or isbn</h4>
    <div class="form-container" id="form-box">
      <%= simple_form_for :search, remote: true, url: dashboard_books_path,
      method: :get, wrapper: :inline_form,
      html: { class: 'form-row mt-3 search-input', id: 'book-search-form' } do |f| %>
        <div class="col-10">
          <%= f.input :query, label: false, class: "form-control string required", placeholder: "Example: 1984" %>
        </div>
        <div class="col-2">
          <%= f.submit "Search", class: "btn btn-block btn-search", id: "search-submit-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="search-results"></div>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bookaroo | Your notes always with you</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="container">
    <div class="page-container">
      <div class="content-wrap">
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
      <%= render '/shared/footer' %>
    </div>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row row-height">
  <div class="vertical-centered-col col-12 col-md-7">
    <div class="call-out d-flex align-items-center">
      <h2 class="">Your</h2>
      <div class="word-list">
        <div>
          <ul class="flip">
            <li>books</li>
            <li>notes</li>
            <li class="underlined">highlights</li>
          </ul>
        </div>
      </div>
    </div>
    <h1>Anywhere, with you.</h1>
  </div>

  <div class="col-md-5 d-none d-md-block">
    <svg class="book-shelf" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="10 10 60 60" height="380" width="380">
      <path fill="none" d="M37.612 92.805L4.487 73.71c-2.75-1.587-4.45-4.52-4.45-7.687L.008 27.877c-.003-3.154 1.676-6.063 4.405-7.634L37.558 1.167c2.73-1.57 6.096-1.566 8.835.013l33.124 19.096c2.75 1.586 4.45 4.518 4.45 7.686l.028 38.146c.002 3.154-1.677 6.063-4.406 7.634L46.445 92.818c-2.73 1.57-6.096 1.566-8.834-.013z"/>
      <g class="book-shelf__book book-shelf__book--one" fill-rule="evenodd">
        <path fill="#464655" d="M26 29h4c1.105 0 2 .895 2 2v29c0 1.105-.895 2-2 2h-4c-1.105 0-2-.895-2-2V31c0-1.105.895-2 2-2z"/>
        <path fill="#8f8fa6" d="M29 36h-2c-.552 0-1-.448-1-1s.448-1 1-1h2c.552 0 1 .448 1 1s-.448 1-1 1zm-2 1h2c.552 0 1 .448 1 1s-.448 1-1 1h-2c-.552 0-1-.448-1-1s.448-1 1-1z"/>
      </g>
      <g class="book-shelf__book book-shelf__book--two" fill-rule="evenodd">
        <path fill="#ff9868" d="M34 34h6c1.105 0 2 .895 2 2v24c0 1.105-.895 2-2 2h-6c-1.105 0-2-.895-2-2V36c0-1.105.895-2 2-2z"/>
        <path fill="#CF5C36" d="M37 38c1.105 0 2 .895 2 2s-.895 2-2 2-2-.895-2-2 .895-2 2-2z"/>
      </g>
      <g class="book-shelf__book book-shelf__book--three" fill-rule="evenodd">
        <path fill="#ff6250" d="M44 32h2c1.105 0 2 .86 2 1.92v25.906c0 1.06-.895 1.92-2 1.92h-2c-1.105 0-2-.86-2-1.92V33.92c0-1.06.895-1.92 2-1.92z"/>
        <path fill="#f7887c" d="M45 35c.552 0 1 .448 1 1v2c0 .552-.448 1-1 1s-1-.448-1-1v-2c0-.552.448-1 1-1z"/>
      </g>
      <g class="book-shelf__book book-shelf__book--four" fill-rule="evenodd">
        <path fill="#464655" d="M50 34h6c1.105 0 2 .895 2 2v24c0 1.105-.895 2-2 2h-6c-1.105 0-2-.895-2-2V36c0-1.105.895-2 2-2z"/>
        <path fill="#8f8fa6" d="M53 38c1.105 0 2 .895 2 2s-.895 2-2 2-2-.895-2-2 .895-2 2-2z"/>
      </g>
      <g fill-rule="evenodd">
        <path class="book-shelf__shelf" fill="#ae8280" d="M21 60h40c1.105 0 2 .895 2 2s-.895 2-2 2H21c-1.105 0-2-.895-2-2s.895-2 2-2z"/>
        <path fill="#855f6d" d="M51.5 67c-.828 0-1.5-.672-1.5-1.5V64h3v1.5c0 .828-.672 1.5-1.5 1.5zm-21 0c-.828 0-1.5-.672-1.5-1.5V64h3v1.5c0 .828-.672 1.5-1.5 1.5z"/>
      </g>
    </svg>
  </div>
</div>

<div class="row service-section text-light">
  <div class="col-12 pl-0">
    <div class="row">
      <div class="col-12 my-5 px-2 px-md-0">
        <div class="card bg-transparent border-0" data-aos="fade-right">
          <div class="row">
            <div class="col-md-2 pl-lg-0">
              <i class="fas fa-book-open d-block text-center"></i>
            </div>
            <div class="col-12 col-md-10 my-auto">
              <div class="card-text text-center text-md-left mt-5 mt-md-0">
                <h5>See your books displayed in a minimal dashboard.</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 my-5 px-2 px-md-0">
        <div class="card bg-transparent border-0" data-aos="fade-right">
          <div class="row">
            <div class="col-md-2 pl-lg-0">
              <i class="fas fa-highlighter d-block text-center"></i>
            </div>
            <div class="col-12 col-md-10 my-auto">
              <div class="card-text text-center text-md-left mt-5 mt-md-0">
                <h5>Gather all your notes and highlights in one place.</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 my-5 px-2 px-md-0">
        <div class="card bg-transparent border-0" data-aos="fade-right">
          <div class="row">
            <div class="col-md-2 pl-lg-0">
              <i class="fas fa-search d-block text-center"></i>
            </div>
            <div class="col-12 col-md-10 my-auto">
              <div class="card-text text-center text-md-left mt-5 mt-md-0">
                <h5>Find a particular note or highlight easily, whenever you need it.</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row footer-call-out text-light">
  <div class="col-12 text-center my-5">
    <h3 class="pt-2 pb-4">Join today</h3>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-gradient my-3' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex flex-column flex-md-row align-items-center justify-content-between">
  <div class="footer-links py-2 py-md-auto">
    <%= link_to "About", "#", class: 'nav-link' %>
    <%= link_to "FAQ", "#", class: 'nav-link' %>
    <%= link_to "Contact", "#", class: 'nav-link' %>
  </div>
  <div class="footer-copyright py-2 py-md-auto">
    Made with <i class="fas fa-heart"></i> by twikah
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", user_root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.png", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>